package Principal;

import Clinica.Orden;
import Clinica.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Clinica.Usuario;

/**
 *
 * @author Fernanda
 */
public class EjecuciónOrdenesyAnalisis extends javax.swing.JFrame {
    private Usuario usuarioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EjecuciónOrdenesyAnalisis.class.getName());
    public static ArrayList<Orden> listaOrdenes = new ArrayList<>();
    private Integer indiceModificar = null;

    public EjecuciónOrdenesyAnalisis(Usuario user) {
        initComponents();
        cargarPacientes();
        actualizarTabla();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public EjecuciónOrdenesyAnalisis() {
        initComponents();
    }

    private void cargarPacientes() {
        comboBoxPaciente.removeAllItems();

        for (Paciente p : GestionPacientes.listaPacientes) {
            comboBoxPaciente.addItem(p.getNombres() + " " + p.getApellidos());
        }
    }

    private void actualizarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Orden ord : EjecuciónOrdenesyAnalisis.listaOrdenes) {
            model.addRow(new Object[]{
                ord.getNombre(),
                ord.getDescripcion(),
                ord.getPrecio(),
                ord.getEstado(),
                ord.getResultado(),
                ord.getPaciente().getNombres() + " " + ord.getPaciente().getApellidos()
            });
        }
    }

    private void limpiarCampos() {
        ComboBoxTipo.setSelectedIndex(0);
        IngresarDescripción.setText("");
        if (comboBoxPaciente.getItemCount() > 0) {
            comboBoxPaciente.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        IngresarDescripción = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxPaciente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Agregarbt = new javax.swing.JToggleButton();
        Modficarbt = new javax.swing.JButton();
        Eliminarbt = new javax.swing.JButton();
        GuardarCambios = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TIPO:");

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden", "Analisis" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        IngresarDescripción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarDescripciónActionPerformed(evt);
            }
        });

        jLabel3.setText("Paciente:");

        comboBoxPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPacienteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Descripción", "Paciente"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Agregarbt.setText("Agregar");
        Agregarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarbtActionPerformed(evt);
            }
        });

        Modficarbt.setText("Modificar");
        Modficarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModficarbtActionPerformed(evt);
            }
        });

        Eliminarbt.setText("Eliminar");
        Eliminarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtActionPerformed(evt);
            }
        });

        GuardarCambios.setText("Guardar Cambios");
        GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Volver");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverloinBt(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarDescripción)
                            .addComponent(comboBoxPaciente, 0, 149, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Agregarbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(GuardarCambios)
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(Modficarbt)
                .addGap(38, 38, 38)
                .addComponent(Eliminarbt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IngresarDescripción, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Agregarbt)
                            .addComponent(GuardarCambios))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modficarbt)
                    .addComponent(Eliminarbt)
                    .addComponent(jToggleButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPacienteActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void IngresarDescripciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarDescripciónActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una orden.");
            return;
        }

        EjecuciónOrdenesyAnalisis.listaOrdenes.remove(fila);
        actualizarTabla();
    }//GEN-LAST:event_IngresarDescripciónActionPerformed

    private void ModficarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModficarbtActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una orden.");
            return;
        }

        Orden ord = EjecuciónOrdenesyAnalisis.listaOrdenes.get(fila);
        indiceModificar = fila;

        ComboBoxTipo.setSelectedItem(ord.getNombre());
        IngresarDescripción.setText(ord.getDescripcion());

        for (int i = 0; i < GestionPacientes.listaPacientes.size(); i++) {
            Paciente p = GestionPacientes.listaPacientes.get(i);
            if (p == ord.getPaciente()) {
                comboBoxPaciente.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_ModficarbtActionPerformed

    private void EliminarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarbtActionPerformed

    private void AgregarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarbtActionPerformed
        String nombre = ComboBoxTipo.getSelectedItem().toString();
        String descripcion = IngresarDescripción.getText();

        int indexPac = comboBoxPaciente.getSelectedIndex();
        if (indexPac == -1) {
            JOptionPane.showMessageDialog(this, "No hay pacientes para seleccionar.");
            return;
        }

        Paciente pac = GestionPacientes.listaPacientes.get(indexPac);
        double precio = 0.0;

        Orden nueva = new Orden(nombre, descripcion, precio, pac);
        EjecuciónOrdenesyAnalisis.listaOrdenes.add(nueva);

        actualizarTabla();
        limpiarCampos();
    }//GEN-LAST:event_AgregarbtActionPerformed

    private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed
        if (indiceModificar == null) {
            JOptionPane.showMessageDialog(this, "No estás modificando ninguna orden.");
            return;
        }

        Orden ord = EjecuciónOrdenesyAnalisis.listaOrdenes.get(indiceModificar);

        ord.setNombre(ComboBoxTipo.getSelectedItem().toString());
        ord.setDescripcion(IngresarDescripción.getText());

        Paciente pac = GestionPacientes.listaPacientes.get(comboBoxPaciente.getSelectedIndex());
        ord.setPaciente(pac);

        indiceModificar = null;
        actualizarTabla();
        limpiarCampos();
    }//GEN-LAST:event_GuardarCambiosActionPerformed

    private void VolverloinBt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverloinBt
        MenudeOpciones menu = new MenudeOpciones(this.usuarioActual);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverloinBt

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EjecuciónOrdenesyAnalisis().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agregarbt;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton Eliminarbt;
    private javax.swing.JToggleButton GuardarCambios;
    private javax.swing.JTextField IngresarDescripción;
    private javax.swing.JButton Modficarbt;
    private javax.swing.JComboBox<String> comboBoxPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
