/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;
import Clinica.Cita;
import Clinica.Consultorio;
import Clinica.Empleado;
import Clinica.Medico;
import Clinica.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class GESTIONCITAS extends javax.swing.JFrame {
    private Clinica.Usuario usuarioActual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GESTIONCITAS.class.getName());

    public static ArrayList<Cita> listaCitas = new ArrayList<>();
    
    public GESTIONCITAS() {
        initComponents();
        cargarListas();
        actualizarTabla();
    }
    public GESTIONCITAS(Clinica.Usuario user) {
        this(); 
        this.usuarioActual = user;
    }
    private void cargarListas() {
        jcbMedicos.removeAllItems();
        for(Empleado emp : Gestor_Empleados.listaEmpleados) {
            if(emp.getRol().equalsIgnoreCase("Médico")) {
                
                jcbMedicos.addItem(emp.getDni() + " - " + emp.getNombres());
            }
        }
        

        jcbPacientes.removeAllItems();
        for(Paciente pac : GestionPacientes.listaPacientes) {
            jcbPacientes.addItem(pac.getDni() + " - " + pac.getNombres());
        }
        

        jcbConsultorios.removeAllItems();
        for(Consultorio con : ConsultasTabla.listaconsultorios) {
            jcbConsultorios.addItem(con.getCodigo() + " - " + con.getEspecialidad());
        }
    }
    private void actualizarTabla() {
        DefaultTableModel model = (DefaultTableModel) jtCitas.getModel();
        model.setRowCount(0);
        
        // Configurar columnas si no están
        if(model.getColumnCount() == 0) {
            model.addColumn("Fecha");
            model.addColumn("Paciente");
            model.addColumn("Médico");
            model.addColumn("Consultorio");
            model.addColumn("Estado");
        }

        for(Cita c : listaCitas) {
            model.addRow(new Object[]{
                c.getFechaHora(),
                c.getPaciente().getNombres(),
                c.getMedico().getNombres(),
                c.getConsultorio().getCodigo(),
                c.getEstado()
            });
        }
    }
    private Medico buscarMedico(String textoCombo) {
        if(textoCombo == null) return null;
        String dni = textoCombo.split(" - ")[0]; 
        for(Empleado emp : Gestor_Empleados.listaEmpleados) {
            if(emp.getDni().equals(dni) && emp instanceof Medico) return (Medico) emp;
        }
        return null;
    }
    
    private Paciente buscarPaciente(String textoCombo) {
        if(textoCombo == null) return null;
        String dni = textoCombo.split(" - ")[0];
        for(Paciente p : GestionPacientes.listaPacientes) {
            if(p.getDni().equals(dni)) return p;
        }
        return null;
    }
    
    private Consultorio buscarConsultorio(String textoCombo) {
        if(textoCombo == null) return null;
        String codigo = textoCombo.split(" - ")[0];
        for(Consultorio c : ConsultasTabla.listaconsultorios) {
            if(c.getCodigo().equals(codigo)) return c;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JButton();
        textMedicos = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        jcbMedicos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbConsultorios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCitas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();
        textPacientes = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        jcbPacientes = new javax.swing.JComboBox<>();
        bVolver = new javax.swing.JToggleButton();
        Modalidad = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        textMedicos.setText("Medicos");

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jcbMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Consultorios");

        jcbConsultorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Estado");

        jLabel1.setText("Datos Citas");

        jtCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha y Hora", "Modalidad", "Estado", "Paciente", "Medico", "Consultorio"
            }
        ));
        jScrollPane3.setViewportView(jtCitas);

        jLabel2.setText("Fecha y Hora");

        textPacientes.setText("Pacientes");

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jcbPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        Modalidad.setText("jTextField1");

        Guardar.setText("Guardar");

        jLabel5.setText("Modalidad:");

        Estado.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(bModificar)
                .addGap(161, 161, 161)
                .addComponent(bEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPacientes)
                    .addComponent(jcbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMedicos)
                    .addComponent(jcbMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Modalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(487, 487, 487))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addGap(77, 77, 77)
                        .addComponent(Guardar)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bVolver)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Modalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textMedicos)
                        .addGap(18, 18, 18)
                        .addComponent(jcbMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Guardar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificar)
                    .addComponent(bEliminar))
                .addGap(7, 7, 7)
                .addComponent(bVolver)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
       if (jcbPacientes.getSelectedItem() == null || jcbMedicos.getSelectedItem() == null || jcbConsultorios.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Faltan datos. Asegúrese de tener pacientes y médicos registrados.");
            return;
        }

        Paciente p = buscarPaciente(jcbPacientes.getSelectedItem().toString());
        Medico m = buscarMedico(jcbMedicos.getSelectedItem().toString());
        Consultorio c = buscarConsultorio(jcbConsultorios.getSelectedItem().toString());
        
        String fecha = Fecha.getText();
        String estado = jcbEstado.getSelectedItem().toString();

        Cita nuevaCita = new Cita(fecha, "Presencial", estado, p, m, c);
        
        listaCitas.add(nuevaCita);
        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Cita Agregada");
    
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        int fila = jtCitas.getSelectedRow();
        if(fila >= 0) {
            Cita c = listaCitas.get(fila);
            c.setEstado(jcbEstado.getSelectedItem().toString());
            actualizarTabla();
            JOptionPane.showMessageDialog(this, "Estado Actualizado");
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una cita de la tabla.");
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int fila = jtCitas.getSelectedRow();
        if(fila >= 0) {
            listaCitas.remove(fila);
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una cita.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        MenudeOpciones menu = new MenudeOpciones(usuarioActual);
        menu.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_bVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GESTIONCITAS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Fecha;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Modalidad;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JToggleButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbConsultorios;
    private javax.swing.JComboBox<String> jcbMedicos;
    private javax.swing.JComboBox<String> jcbPacientes;
    private javax.swing.JTable jtCitas;
    private javax.swing.JLabel textMedicos;
    private javax.swing.JLabel textPacientes;
    // End of variables declaration//GEN-END:variables
}
