
package Principal;

import GestionClinica.GestionPacientes;
import Clinica.Paciente;
import Principal.Sistema;
import javax.swing.table.DefaultTableModel;


public class GESTIONPACIENTESPANEL extends javax.swing.JPanel {

    private Sistema sistema;
    private int indiceSeleccionado = -1;

    public GESTIONPACIENTESPANEL(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Volverbt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Contacto_Emergencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Dni = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Fecha_Nacimiento = new javax.swing.JTextField();
        Sexo = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Direccion = new javax.swing.JTextField();
        GuardarCambiosbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DNIextfieldeliminar = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Fecha Nacimiento", "Sexo", "Telefono", "Dirección", "Contacto de Emergencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Volverbt.setText("Volver");
        Volverbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverbtActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        jLabel7.setText("Sexo:");

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel9.setText("Telefono:");

        Dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        GuardarCambiosbt.setText("Guardar Cambios");
        GuardarCambiosbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosbtActionPerformed(evt);
            }
        });

        jLabel1.setText("Dni:");

        jLabel2.setText("Contacto de Emergencia:");

        jLabel3.setText("Apellido:");

        jLabel8.setText("Dirección:");

        DNIextfieldeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIextfieldeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Modificar)
                        .addGap(38, 38, 38)
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(DNIextfieldeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volverbt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Aceptar)
                        .addGap(97, 97, 97)
                        .addComponent(GuardarCambiosbt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contacto_Emergencia, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(Fecha_Nacimiento)
                            .addComponent(Sexo)
                            .addComponent(Telefono)
                            .addComponent(Direccion)
                            .addComponent(Nombre)
                            .addComponent(Apellido)
                            .addComponent(Dni))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contacto_Emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Aceptar)
                            .addComponent(GuardarCambiosbt))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(Eliminar)
                    .addComponent(Volverbt)
                    .addComponent(DNIextfieldeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un paciente para modificar.");
            return;
        }

        indiceSeleccionado = fila;

        Paciente p = sistema.getGestionPacientes().getPaciente(fila);

        Dni.setText(p.getDni());
        Nombre.setText(p.getNombres());
        Apellido.setText(p.getApellidos());
        Fecha_Nacimiento.setText(p.getFechaNacimiento());
        Sexo.setText(p.getSexo());
        Telefono.setText(p.getTelefono());
        Direccion.setText(p.getDireccion());
        Contacto_Emergencia.setText(p.getContactoEmergencia());

    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String dniEliminar = DNIextfieldeliminar.getText().trim();

        if (dniEliminar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el DNI del paciente a eliminar.");
            return;
        }

        boolean eliminado = sistema.getGestionPacientes().eliminar(dniEliminar);

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente eliminado correctamente.");
            actualizarTabla();
            DNIextfieldeliminar.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un paciente con ese DNI.");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void VolverbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverbtActionPerformed
        MenudeOpciones menu = new MenudeOpciones(sistema.getUsuarioActual(), sistema);
        menu.setSize(800, 600);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);

        // Cerrar la ventana actual
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    
    }//GEN-LAST:event_VolverbtActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String dni = Dni.getText().trim();
        String nombre = Nombre.getText().trim();
        String apellido = Apellido.getText().trim();
        String fecha = Fecha_Nacimiento.getText().trim();
        String sexo = Sexo.getText().trim();
        String telefono = Telefono.getText().trim();
        String direccion = Direccion.getText().trim();
        String contacto = Contacto_Emergencia.getText().trim();
        if (dni.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete al menos DNI, Nombre y Apellido.");
            return;
        }
        Paciente nuevo = new Paciente(
                dni,
                nombre,
                apellido,
                fecha,
                sexo,
                telefono,
                direccion,
                contacto
        );

        boolean agregado = sistema.getGestionPacientes().agregar(nuevo);

        if (agregado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente agregado correctamente.");
            actualizarTabla();
            limpiarCampos();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo agregar el paciente (lista llena).");
        }

    }//GEN-LAST:event_AceptarActionPerformed

    private void GuardarCambiosbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosbtActionPerformed
        if (indiceSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay paciente seleccionado para modificar.");
            return;
        }

        Paciente p = sistema.getGestionPacientes().getPaciente(indiceSeleccionado);

        p.setDni(Dni.getText());
        p.setNombres(Nombre.getText());
        p.setApellidos(Apellido.getText());
        p.setFechaNacimiento(Fecha_Nacimiento.getText());
        p.setSexo(Sexo.getText());
        p.setTelefono(Telefono.getText());
        p.setDireccion(Direccion.getText());
        p.setContactoEmergencia(Contacto_Emergencia.getText());

        actualizarTabla();
        limpiarCampos();
        indiceSeleccionado = -1;

        javax.swing.JOptionPane.showMessageDialog(this, "Paciente modificado correctamente.");
    }//GEN-LAST:event_GuardarCambiosbtActionPerformed

    private void DniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniActionPerformed

    private void DNIextfieldeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIextfieldeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIextfieldeliminarActionPerformed
    private void actualizarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    GestionPacientes gp = sistema.getGestionPacientes();

    for (int i = 0; i < gp.getCantidad(); i++) {
        Paciente p = gp.getPaciente(i);

        modelo.addRow(new Object[]{
            p.getDni(),
            p.getNombres(),
            p.getApellidos(),
            p.getFechaNacimiento(),
            p.getSexo(),
            p.getTelefono(),
            p.getDireccion(),
            p.getContactoEmergencia()
        });
    }
}

    private void limpiarCampos() {
    Dni.setText("");
    Nombre.setText("");
    Apellido.setText("");
    Fecha_Nacimiento.setText("");
    Sexo.setText("");
    Telefono.setText("");
    Direccion.setText("");
    Contacto_Emergencia.setText("");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Contacto_Emergencia;
    private javax.swing.JTextField DNIextfieldeliminar;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Dni;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Fecha_Nacimiento;
    private javax.swing.JButton GuardarCambiosbt;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Sexo;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton Volverbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
