/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Clinica.Usuario;

/**
 *
 * @author Nicol
 */
public class MenudeOpciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenudeOpciones.class.getName());

    /**
     * Creates new form MenudeOpciones
     */
    public MenudeOpciones(Usuario user) {
        initComponents();
        deshabilitarTodo();  
        switch (user.getRol()){
            case "Administrador":
                GEmpleados.setEnabled(true);
                GConsultorios.setEnabled(true);
                HistorialClinica.setEnabled(true);
                Reportes.setEnabled(true);
                break;
            case "Médico":
                Consultas.setEnabled(true);          
                AtencionClinica.setEnabled(true);
                HistorialClinica.setEnabled(true);
                EjecucionOrdenesAnalisis.setEnabled(true);
                break;
            case "Enfermero":
                AdmisionyAlta.setEnabled(true);
                EjecucionOrdenesAnalisis.setEnabled(true);
                AtencionClinica.setEnabled(true); 
                break;
            case "Cajero":
                Facturas.setEnabled(true);
                break;
            case "Recepcionista":
                GestionPacientes.setEnabled(true);
                Consultas.setEnabled(true);          
                AdmisionyAlta.setEnabled(true);
                Facturas.setEnabled(true); 
                break;
        }
        
    }
    
    private void deshabilitarTodo() {
        GEmpleados.setEnabled(false);
        GConsultorios.setEnabled(false);
        GestionPacientes.setEnabled(false);
        Consultas.setEnabled(false);
        AdmisionyAlta.setEnabled(false);
        AtencionClinica.setEnabled(false);
        EjecucionOrdenesAnalisis.setEnabled(false);
        HistorialClinica.setEnabled(false);
        Facturas.setEnabled(false);
        Reportes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GEmpleados = new javax.swing.JMenuItem();
        GConsultorios = new javax.swing.JMenuItem();
        GestionPacientes = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenuItem();
        AdmisionyAlta = new javax.swing.JMenuItem();
        AtencionClinica = new javax.swing.JMenuItem();
        EjecucionOrdenesAnalisis = new javax.swing.JMenuItem();
        HistorialClinica = new javax.swing.JMenuItem();
        Facturas = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");

        GEmpleados.setText("Gestion Empleados");
        GEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(GEmpleados);

        GConsultorios.setText("Gestion Consultorios");
        GConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GConsultoriosActionPerformed(evt);
            }
        });
        jMenu1.add(GConsultorios);

        GestionPacientes.setText("Gestion Pacientes");
        jMenu1.add(GestionPacientes);

        Consultas.setText("Consultas");
        jMenu1.add(Consultas);

        AdmisionyAlta.setText("Admision y Alta");
        jMenu1.add(AdmisionyAlta);

        AtencionClinica.setText("Atencion Clinica");
        jMenu1.add(AtencionClinica);

        EjecucionOrdenesAnalisis.setText("Ejecucion Ordenes Analisis");
        jMenu1.add(EjecucionOrdenesAnalisis);

        HistorialClinica.setText("Historial Clinica");
        jMenu1.add(HistorialClinica);

        Facturas.setText("Facturas y Pagos");
        jMenu1.add(Facturas);

        Reportes.setText("Reportes");
        jMenu1.add(Reportes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GConsultoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GConsultoriosActionPerformed

    private void GEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GEmpleadosActionPerformed
        // TODO add your handling code here:
        Gestor_Empleados gestor = new Gestor_Empleados();
        gestor.setVisible(true);

    // Cerrar u ocultar la ventana actual del menú
        this.dispose();  // si quieres cerrar el menú completamente
// this.setVisible(false)
    }//GEN-LAST:event_GEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenudeOpciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdmisionyAlta;
    private javax.swing.JMenuItem AtencionClinica;
    private javax.swing.JMenuItem Consultas;
    private javax.swing.JMenuItem EjecucionOrdenesAnalisis;
    private javax.swing.JMenuItem Facturas;
    private javax.swing.JMenuItem GConsultorios;
    private javax.swing.JMenuItem GEmpleados;
    private javax.swing.JMenuItem GestionPacientes;
    private javax.swing.JMenuItem HistorialClinica;
    private javax.swing.JMenuItem Reportes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
